scheming_version: 1
about: 'Statistics Canada Dissemination: Services'
about_url: http://github.com/open-data/ckanext-stcndm
catalog_type_label:
  en: Services
  fr: Services
dataset_type: service
form_languages:
- en
- fr
languages_label:
- eng; CAN
- fra; CAN

lookup_key: product_id_new

dataset_fields:

- field_name: owner_org
  preset: ndm_owner_org

- field_name: admin_notes
  preset: ndm_admin_notes

- field_name: title
  preset: ndm_title

- field_name: notes
  preset: ndm_description

- field_name: content_type_codes
  preset: ndm_content_type_codes

- field_name: geolevel_codes
  preset: ndm_geolevel_codes

- field_name: geodescriptor_codes
  preset: ndm_geodescriptor_codes

- field_name: subject_codes
  preset: ndm_subject_codes

- field_name: name
  preset: ndm_name
  # follow our custom name generation with default package name validators
  validators: service_create_name
    not_empty unicode name_validator package_name_validator

- field_name: product_type_code
  label:
    en: Product Type
    fr: Type de produit
  preset: select
  choices:
    - label:
        en: Service
        fr: Service
      value: '23'
  required: true

- field_name: related_products
  preset: ndm_related_products

- field_name: thesaurus_terms
  preset: ndm_thesaurus_terms

- field_name: feature_weight
  preset: ndm_feature_weight

- field_name: archive_date
  preset: ndm_archive_date

- field_name: archive_status_code
  preset: ndm_archive_status

- field_name: tracking_codes
  preset: ndm_tracking

- field_name: digital_object_identifier
  preset: ndm_digital_object_identifier

- field_name: array_terminated_code
  preset: ndm_array_terminated

#- field_name: default_view_id
#  label:
#    en: Default View ID
#    fr: ID de vue par défaut

- field_name: dimension_members
  preset: ndm_dimension_members

- field_name: external_authors
  preset: ndm_external_authors

- field_name: frc
  preset: ndm_frc

- field_name: frequency_codes
  preset: ndm_frequency_codes

- field_name: history_notes
  preset: ndm_history_notes

- field_name: survey_source_codes
  preset: ndm_survey_source_codes

- field_name: internal_authors
  preset: ndm_internal_authors

- field_name: internal_contacts
  preset: ndm_internal_contacts

- field_name: keywords
  preset: ndm_keywords

- field_name: last_publish_status_code
  preset: ndm_publish_status

- field_name: legacy_date
  preset: ndm_legacy_date

- field_name: top_parent_id
  preset: ndm_top_parent_id

- field_name: price
  preset: ndm_price

- field_name: price_note
  preset: ndm_price_note

- field_name: product_id_new
  preset: ndm_product_id_new

- field_name: product_id_old
  preset: ndm_product_id_old

- field_name: publication_year
  preset: ndm_publication_year

#- field_name: reference_periods
#  label:
#    en: Reference Period
#    fr: Période de référence
#  preset: fluent_tags
#  tag_validators: ndm_tag_name_validator tag_length_validator

- field_name: replaced_products
  preset: ndm_replaced_products

- field_name: status_code
  preset: ndm_status

- field_name: discontinued_code
  preset: ndm_discontinued_code

- field_name: discontinued_date
  preset: ndm_discontinued_date

- field_name: census_grouping_code
  preset: ndm_census_grouping

- field_name: load_to_olc_code
  preset: ndm_load_to_olc_code

- field_name: subjectold_codes
  preset: ndm_subjectold_codes
